### ISSUE TITLE
ts-mapstruct is not working with sequelizer

### ISSUE THREAD

**Issue by sartajg** [ugoevola/ts-mapstruct#17]
Not sure what is wrong, but getting this error while mapping properties.
Entities are annotated with sequelizer and DTO are having normal attributes 

throw new model_not_initialized_error_1.ModelNotInitializedError(new.target, `${new.target.name} cannot be instantiated.`);
                  ^
Error: Model not initialized: PersonEntity cannot be instantiated. "PersonEntity" needs to be added to a Sequelize instance.

**Comment by ugoevola** [comment]
can you please indicate your dto, your entity, and your mapper?
This would help me to solve the problem

**Comment by ugoevola** [comment]
Is this the problem mentioned below : 
https://github.com/sequelize/sequelize-typescript/issues/366
