### ISSUE TITLE
How to map array types?

### ISSUE THREAD

**Issue by mov37** [ugoevola/ts-mapstruct#19]
The doc seems say to little about how to map array of types.

For example, suppose I have two similar classes:

```ts


export class ContactCO {
  countryCode: string;
  cityCode: string;
  phone: string;
  extensionNo: string;
}

// ---

export class ContactNumber {
    countryCode?: Nullable<string>;
    areaCode?: Nullable<string>;
    main?: Nullable<string>;
    extension?: Nullable<string>;
    phone?: Nullable<string>;
}
```

and I want to map `ContactCO[]` into `ContactPhone[]`, how can I write the mapping options?

```ts
// this seems doesn't work as expected
@Mapping(
    {
      target: "contactNumbers",
      source: "useRuleCO.contactList",
      type: ContactNumber,
    },
    {
      target: "contactNumbers.main",
      source: "useRuleCO.contactList.phone", // convert phone field into main field
    },
)
```

does ts-mapstruct supports this kind of auto mapping?

**Comment by ugoevola** [comment]
Hello,

It seems to be a bug,
I work on a fix

Thank's for your feedback !

**Comment by ugoevola** [comment]
A new version "3.2.0" has just been released.

It should correct some problems with array mapping, so your solution should work.
But there are still some unexpected behaviors with array mapping.

I think the library needs a refactoring, and this will be for a new major version later.

leave me a comment to say if it works now
